[workspace]
resolver = "3"
members = ["crates/*"]
default-members = ["crates/git_diff_sync_cli"]

[workspace.package]
edition = "2024"
authors = ["Steveplays28"]
homepage = "https://steveplays.com"
repository = "https://github.com/Steveplays28/git_diff_sync"
license = "GPL-3.0-only"
readme = "README.md"
description = "Synchronize uncommitted Git changes to other devices."
keywords = ["git", "synchronization", "git-diff", "rocket"]
categories = ["command-line-utilities"]
