[package]
name = "git_diff_sync_server"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme.workspace = true
description.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive", "cargo", "string"] }
directories = "6.0.0"
figment = { version = "0.10.19", features = ["env"] }
glob = "0.3.3"
rocket = { git = "https://github.com/rwf2/Rocket.git", rev = "504efef179622df82ba1dbd37f2e0d9ed2b7c9e4" }
serde = { version = "1.0.227", features = ["derive"] }
static_init = "1.0.4"
thiserror = "2.0.16"
