name: Continuous integration
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          rustup toolchain install
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install mold clang
          cargo test --all

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          rustup toolchain install
          rustup component add rustfmt
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install mold clang
          cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: |
          rustup toolchain install
          rustup component add clippy
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install mold clang
          cargo clippy --all -- -D warnings
